//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChurrasDaTrinca.DB.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Churrasco
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Churrasco()
        {
            this.ChurrascoParticipantes = new HashSet<ChurrascoParticipante>();
        }
    
        public int Id { get; set; }
        public System.DateTime Data { get; set; }
        public string Razao { get; set; }
        public string Obs { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChurrascoParticipante> ChurrascoParticipantes { get; set; }
    }
}
