//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChurrasDaTrinca.DB.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChurrascoParticipante
    {
        public int Id { get; set; }
        public int IdChurrasco { get; set; }
        public int IdParticipante { get; set; }
        public Nullable<decimal> Contribuicao { get; set; }
        public bool CheckBebida { get; set; }
        public bool CheckPago { get; set; }
        public string Obs { get; set; }
    
        public virtual Churrasco Churrasco { get; set; }
        public virtual Participante Participante { get; set; }
    }
}
