//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChurrasDaTrinca.DB.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CHURRASEntities : DbContext
    {
        public CHURRASEntities()
            : base("name=CHURRASEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Churrasco> Churrascoes { get; set; }
        public virtual DbSet<ChurrascoParticipante> ChurrascoParticipantes { get; set; }
        public virtual DbSet<Participante> Participantes { get; set; }
    }
}
